<?php

namespace CRWorks\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CRUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CRUserRepository extends EntityRepository
{
}
